name: GitHub Actions Demo
on: [push]
jobs:
  test:
    steps:
      - name: 24f1001599@ds.study.iitm.ac.in
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

